export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

// FETCH BLOCKS
export const FETCH_BLOCKS_STATUS_START = 'FETCH_BLOCKS_STATUS_START';
export const FETCH_BLOCKS_STATUS_SUCCESS = 'FETCH_BLOCKS_STATUS_SUCCESS';
export const FETCH_BLOCKS_STATUS_FAILURE = 'FETCH_BLOCKS_STATUS_FAILURE';
